import Sidebar from "./Sidebar";
import "../globals.css";
import localFont from "next/font/local";

const manrope = localFont({
  src: [
    {
      path: "../../public/fonts/Manrope-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../../public/fonts/Manrope-Bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/Manrope-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/Manrope-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/Manrope-Light.ttf",
      weight: "300",
    },
  ],
  variable: "--font-manrope",
});

export const metadata = {
  title: "my blog",
  description: "Generated by create next app",
  openGraph: {
    title: "Lee Robinson",
    description: "Developer, writer, and creator.",
    url: "https://leerob.io",
    siteName: "Lee Robinson",
    images: [
      {
        url: "https://leerob.io/og.jpg",
        width: 1920,
        height: 1080,
      },
    ],
    locale: "en-US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    title: "Lee Robinson",
    card: "summary_large_image",
  },
  icons: {
    shortcut: "/favicon.ico",
  },
  verification: {
    google: "eZSdmzAXlLkKhNJzfgwDqWORghxnJ8qR9_CHdAh5-xw",
    yandex: "14d2e73487fa6c71",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${manrope.variable} font-sans`}>
      <body
        className={`h-[calc(100vh - 128px)]  antialiased max-w-4xl flex flex-col md:flex-row mx-4 lg:mx-auto md:mt-32 mt-14`}
      >
        <Sidebar />
        <main className="flex-auto min-w-0 mt-6 md:mt-0 flex flex-col px-2 md:px-0">
          {children}
          {/* <Analytics /> */}
        </main>
      </body>
    </html>
  );
}
